<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:aop="http://www.springframework.org/schema/aop"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans.xsd
http://www.springframework.org/schema/aop
http://www.springframework.org/schema/aop/spring-aop.xsd">
	
	<bean id="demo" class="com.test.Demo"></bean>
	<bean id="myadvice" class="com.advice.MyAdvice"></bean>
	
	<aop:config>
		<aop:aspect ref="myadvice">
			<aop:pointcut expression="execution(* com.test.Demo.demo1(String,int)) and args(name111,age111)" id="mypoint1"/>
			<aop:pointcut expression="execution(* com.test.Demo.demo2(String)) and args(name11)" id="mypoint2"/>
			<aop:pointcut expression="execution(* com.test.Demo.demo3(String)) and args(name12)" id="mypoint3"/>
			<aop:pointcut expression="execution(* com.test.Demo.demo4(String)) and args(name13)" id="mypoint4"/>
			<aop:pointcut expression="execution(* com.test.Demo.demo5())" id="mypoint5"/>
			<aop:pointcut expression="execution(* com.test.Demo.demo6())" id="mypoint6"/>
			
			<aop:before method="mybefore" pointcut-ref="mypoint1" arg-names="name111,age111"/>
			<aop:before method="mybefore1" pointcut-ref="mypoint2" arg-names="name11"/>
			
			<!-- 不管是否出异常都会走 -->
			<aop:after method="myafter1" pointcut-ref="mypoint3" arg-names="name12"/>
			<!-- 如果出异常就不走了 -->
			<aop:after-returning method="myafter2" pointcut-ref="mypoint4" arg-names="name13"/>
			
			<aop:around method="myarround" pointcut-ref="mypoint5"/>
			
			<aop:after-throwing method="myexception" pointcut-ref="mypoint6" throwing="e1"/>
		</aop:aspect>
	</aop:config>
</beans>